### PR TITLE
Revert 190 revert 187 staging

### PR DESCRIPTION
**Pull request by idmken**
Revert updates when Federalist IDM.gov goes live on July 16th.

### CODE REVIEW

**Comment by idmken** [comment]
@JBPayne007 can you review, but not merge. Thank you.

**Review by JBPayne007 — COMMENTED** [review]
If I approve this it will also merge it. I have just reviewed and added this comment.

**Comment by idmken** [comment]
Fixes #165

**Comment by idmken** [comment]
> If I approve this it will also merge it. I have just reviewed and added this comment.

Great, thanks @JBPayne007

**Pull request merged**
