### PR TITLE
0120 PIV Auth on macOS

### PR DESCRIPTION
**Pull request by idmken**
@maxwellfunk I reviewed this and made a few updates after testing. Please review for consistency.

### CODE REVIEW

**Comment by idmken** [comment]
fixed #80

**Review by JBPayne007 — APPROVED** [review]

**Review by JillTunick — COMMENTED** [review]
The link in line 48 opens to a 404 page. Everything else looks good. I went into the md page and made a few editorial and punctuation changes.

**Review by maxwellfunk — APPROVED** [review]
This guide reads well and has a logical flow.  I did have to correct three links which are working now.

**Comment by idmken** [comment]
Thanks everyone.

**Pull request merged**
