### PR TITLE
auto fpki graph update (20210510)

### PR DESCRIPTION
**Pull request by ryancdickson**
@idmken 

Please find this week's Federal PKI Crawler/Graph update (May 11, 2021 execution). 

<br>

**Live Preview:** https://federalist-db14ea61-37f0-44fd-8ab9-591433f0ec2b.app.cloud.gov/preview/gsa/ficam-playbooks/20210510-auto-fpki-graph-update/fpki/tools/fpkigraph/

<br>

**Nodes Added or Removed (compared to May 03, 2021 execution):**
- N1 (ADDED): CN=Exostar Federated Identity Service Signing CA 4, DC=evincible, DC=com  

<br>

**Edges Added or Removed (compared to May 03, 2021 execution):**
- E1 (REMOVED): CN=Carillon Federal Services PIV-I CA2, OU=Certification Authorities, O=Carillon Federal Services Inc., C=US -> CN=TSCP SHA256 Bridge CA, OU=CAs, O=TSCP Inc., C=US
- E2 (ADDED): CN=Exostar Federated Identity Service Root CA 2, OU=Certification Authorities, O=Exostar LLC, C=US -> CN=Exostar Federated Identity Service Signing CA 4, DC=evincible, DC=com

<br>

**Root Cause Analysis:**
- N1/E2: New certificate detected (Repository Update). Exostar updated http://www.fis.evincible.com/fis/public/ExostarFederatedIdentityServiceRootCA2.p7c to add the following certificate: 
     - Subject: CN=Exostar Federated Identity Service Signing CA 4, DC=evincible, DC=com  
     - Issuer: CN=Exostar Federated Identity Service Root CA 2, OU=Certification Authorities, O=Exostar LLC, C=US 
     - Validity: September 30, 2020 to January 25, 2030
     - Serial: 2e000000070c47ed3776b35fc0000000000007         
     - SHA1 Hash: d5f180db664ec80be77d9bfd5484a50cece5a58d        
     - Key Size: 2048-bit (RSA)
     - Signing Algorithm: SHA-256 with RSA
	 - Note: the certificate above replaced the expired certificate issued from Exostar Federated Identity Service Root CA 2 to the Federal Bridge CA 2016.  A System Notification was added for this issuance event on October 13, 2020.
- E1: Certificate expiration. The following certificate is now expired:
     - Subject: CN=TSCP SHA256 Bridge CA, OU=CAs, O=TSCP Inc., C=US 
     - Issuer: CN=Carillon Federal Services PIV-I CA2, OU=Certification Authorities, O=Carillon Federal Services Inc., C=US 
     - Validity: May 1, 2020 to May 6, 2021 
     - Serial: 02033041b6cc816890551d8d67613620552d         
     - SHA1 Hash: e8f69aa3145f88e437e9cf866a719997da018ff6         
     - Key Size: 2048-bit (RSA)
     - Signing Algorithm: SHA-256 with RSA

<br>

**Other updates:**
- Federal Common Policy CA Migration Playbook
     - Removed the "upcoming event" info alert box from the homepage (no additional events planned at this time)

### CODE REVIEW

**Comment by JBPayne007** [comment]
Looks good.

**Review by idmken — APPROVED** [review]
Looks good.

**Comment by idmken** [comment]
@ryancdickson You included graph updates but I didn't see the graph file was updated. Did I miss something?

**Comment by ryancdickson** [comment]
I just diffed the files (last week and this week) and they are identical.  Let me run it fresh again.

**Comment by ryancdickson** [comment]
@idmken + @JBPayne007 - fresh execution just added!

**Review by idmken — APPROVED** [review]
Looks good.

**Pull request merged**
